components/Footer/Footer.tsx, components/Header/Header.tsx, components/NavigationItems/NavigationItems.tsx, components/SocialMedia/SocialMedia.tsx
Null check added in footer, header, navigation items, social media
=> Null check added in footer, header, navigation items, social media

common/getFooterData/getFooterData.tsx, common/getHeaderData/getHeaderData.tsx, components/Layout/Layout.tsx
code refactored for get header and footer data in layout
=> code refactored for get header and footer data in layout

components/Tabs/Tabs.tsx, components/Tabs/Variants/Horizontal.tsx, components/Tabs/Variants/Vertical.tsx, utils/lib/ComponentFactory.ts
=> code changes for tab

components/Container/Container.tsx, utils/lib/ComponentFactory.ts
=> code changes

components/Footer/Footer.tsx, components/Header/Header.tsx, components/ImageWithTitleDescription/Variants/Default.tsx, components/SearchBox/SearchBox.tsx, styles/globals.css
=> logo visible and added link

utils/lib/ComponentFactory.ts
component entry added in component factory
=> component entry added in component factory

components/Footer/Footer.tsx, components/Footer/footer.css, components/Header/Header.tsx, components/Header/header.css, components/LinkList/LinkList.tsx, components/SearchBox/SearchBox.tsx, styles/globals.css, utils/fonts.tsx
header and footer fonts and style
=> header and footer fonts and style

components/CTA/CTA.tsx, components/Container/Container.tsx, components/FeatureCard/FeatureCard.tsx, components/Footer/Footer.tsx, components/ImageWithTitleDescription/Variants/Default.tsx, components/Layout/Layout.tsx, components/RichText/RichText.tsx, components/SocialMedia/SocialMedia.tsx, components/Tabs/Variants/Horizontal.tsx, styles/globals.css, tailwind.config.ts, utils/fonts.tsx
=> inner page style with font

components/LanguageSelector/LanguageSelector.tsx, next.config.ts, pages/[[...slug]].tsx, utils/utilityFunctions/getEntriesByContentType.ts
code changes to implement the multilingual
=> code changes to implement the multilingual

components/LanguageSelector/LanguageSelector.tsx, pages/[[...slug]].tsx
code changes to fix the multilingual for homepage
=> code changes to fix the multilingual for homepage

components/HeadScript/HeadScript.tsx, utils/lib/ComponentFactory.ts
=> head script code changes

components/LinkList/LinkList.tsx, components/Lisiting/Lisitng.tsx, components/NavigationItems/NavigationItems.tsx, components/SearchBox/SearchBox.tsx, pages/[[...slug]].tsx, pages/blog/[slug].tsx, utils/utilityFunctions/makeRelativeURL.ts
=> blog landing page implemented

components/HeadScript/HeadScript.tsx
using next head instead of next script
=> using next head instead of next script

components/GoogleAnalytics/GoogleAnalytics.tsx, package.json, utils/lib/ComponentFactory.ts
=> implemented google analytics

common/getGoogleAnalyticsData/getGoogleAnalyticsData.tsx, components/Layout/Layout.tsx, utils/lib/ComponentFactory.ts
integrate GoogleAnalyticsComponent in Layout to render on all pages
=> integrate GoogleAnalyticsComponent in Layout to render on all pages

styles/site1.css
Updated CSS to change the background color to white for site1.
=> Updated CSS to change the background color to white for site1.

components/HeroBanner/HeroBannerComponent.tsx, components/Layout/Layout.tsx, components/SEO/SEO.tsx, pages/[[...slug]].tsx, pages/_app.tsx
=> seo code optimized

components/Layout/Layout.tsx
cookie bot initial script setup
=> cookie bot initial script setup

components/ExternalApiResults/ExternalApiReslts.tsx, utils/lib/ComponentFactory.ts
Created a component to feth data from external url
=> Component ExternalApiCreated

components/Container/Container.tsx, components/FeatureCard/FeatureCard.tsx, components/Header/Header.tsx, components/HeroBanner/HeroBannerComponent.tsx, components/ImageWithTitleDescription/Variants/Default.tsx, components/ImageWithTitleDescription/Variants/LeftSideImage.tsx, components/ImageWithTitleDescription/Variants/RightSideImage.tsx, components/NotFound/NotFound.tsx, components/NotFound500/NotFound500.tsx, components/RichText/RichText.tsx, components/Tabs/Variants/Horizontal.tsx, pages/404.tsx, pages/500.tsx, styles/site1.css, styles/site2.css
Feature/added header footer 404
=> Feature/added header footer 404 

components/Container/Container.tsx, components/FeatureCard/FeatureCard.tsx, components/Header/Header.tsx, components/HeroBanner/HeroBannerComponent.tsx, components/ImageWithTitleDescription/Variants/Default.tsx, components/ImageWithTitleDescription/Variants/LeftSideImage.tsx, components/ImageWithTitleDescription/Variants/RightSideImage.tsx, components/RichText/RichText.tsx, components/Tabs/Variants/Horizontal.tsx, styles/site1.css, styles/site2.css
=> designed-responsive-pages

components/HeroBanner/HeroBannerComponent.tsx, package.json
1 Optimized Hero Image 
2 Ensured full URL with https:
3 Description (Rich Text)
=> Light house Fixes

components/HeroBanner/HeroBannerComponent.tsx
=> added loading eager.

components/Footer/Footer.tsx, components/Header/Header.tsx, components/SocialMedia/SocialMedia.tsx
removed unoptimized for both side header and footer
=> removed unoptimized for both side header and footer

components/Header/Header.tsx
src changes to fix the not found issue fro header logo
=> src changes to fix the not found issue fro header logo

components/HeroBanner/HeroBannerComponent.tsx
next try to remove lcp iissue from banner component
=> next try to remove lcp iissue from banner component
